const mongoose = require('mongoose');
const JournalEntry = require('../models/JournalEntry');
const AccountBalance = require('../models/AccountBalance');
const cacheService = require('../services/cacheService');
const { CHART_OF_ACCOUNTS, getAccount, DEFAULT_ACCOUNTS, canPostToAccount } = require('../constants/chartOfAccounts');
const accountMappingService = require('./accountMappingService');
const periodService = require('./periodService');
const { BankAccount } = require('../models/BankAccount');
const { PettyCashFloat } = require('../models/PettyCash');
const TaxTransactionService = require('./taxTransactionService');
const bankTransactionService = require('./bankTransactionService');

/**
 * Validate that an account allows direct posting before creating journal lines
 * This prevents posting to header/summary accounts
 */
function validateAccountForPosting(accountCode, accountName = '') {
  const result = canPostToAccount(accountCode);
  if (!result.valid) {
    const error = new Error(`ACCOUNT_NO_POSTING: Account ${accountCode} (${accountName || 'Unknown'}) is a header/summary account and cannot be posted to directly. Reason: ${result.reason}`);
    error.code = 'ACCOUNT_NO_POSTING';
    error.accountCode = accountCode;
    throw error;
  }
  return true;
}

/**
 * Journal Entry Service
 * Handles automatic creation of journal entries for all financial transactions
 */

class JournalService {
  /**
   * Create a journal entry with multiple lines
   * Ensures debits equal credits
   */
  static async createEntry(companyId, userId, options) {
    const {
      date = new Date(),
      description,
      sourceType = 'manual',
      sourceId = null,
      sourceReference = null,
      lines = [],
      isAutoGenerated = false,
      notes = ''
    } = options;

    // Normalize and validate companyId/userId
    if (userId && typeof userId === 'object' && userId._id) userId = userId._id;
    if (!companyId) throw new Error('Missing companyId when creating journal entry');
    if (!userId) throw new Error('Missing userId when creating journal entry');

    // Validate lines
    if (lines.length < 2) {
      throw new Error('Journal entry must have at least 2 lines');
    }

    // Validate each account allows direct posting (per system-wide rule)
    for (const line of lines) {
      const accountCode = line.accountCode;
      const accountName = line.accountName || '';
      validateAccountForPosting(accountCode, accountName);
    }

    // Idempotency: if a sourceType + sourceId is provided, return existing entry
    // to avoid creating duplicate journal entries for the same source event.
    // Callers may set `options.allowDuplicate` to true to bypass this check
    // (used when intentionally creating multiple auto-generated entries
    // for the same source in a single atomic operation).
    if (sourceType && sourceId && !options.allowDuplicate) {
      try {
        const existing = await JournalEntry.findOne({ company: companyId, sourceType, sourceId });
        if (existing) return existing;
      } catch (err) {
        // Non-fatal - proceed to create and rely on unique index to prevent duplicates
      }
    }

    // Helper to coerce Decimal128/string/number to Number
    const coerceAmount = (v) => {
      if (v == null) return 0;
      if (typeof v === 'number') return v;
      if (typeof v === 'string') return Number(v);
      if (typeof v === 'object') {
        if (v.toString) {
          try { return Number(v.toString()); } catch (e) { return 0; }
        }
      }
      return Number(v) || 0;
    };

    // Calculate totals (coerce Decimal128 values)
    const totalDebit = lines.reduce((sum, line) => sum + coerceAmount(line.debit), 0);
    const totalCredit = lines.reduce((sum, line) => sum + coerceAmount(line.credit), 0);

    // Period lock check - ensure target date is not within a closed period
    const targetDate = date instanceof Date ? date : new Date(date);
    if (await periodService.isDateInClosedPeriod(companyId, targetDate)) {
      const err = new Error('Target accounting period is closed');
      err.code = 'PERIOD_CLOSED';
      throw err;
    }

    // Validate balance
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new Error(`Journal entry is not balanced. Debits: ${totalDebit}, Credits: ${totalCredit}`);
    }

    // Generate entry number
    const entryNumber = await JournalEntry.generateEntryNumber(companyId);

    // Prepare document
    const doc = {
      company: companyId,
      entryNumber,
      date,
      description,
      sourceType,
      sourceId,
      sourceReference,
      reference: sourceReference,
      lines,
      totalDebit,
      totalCredit,
      isAutoGenerated,
      createdBy: userId,
      postedBy: userId,
      status: 'posted',
      notes
    };

      // If caller provided a session, use it. Otherwise, attempt to run in a transaction
      const session = options.session || null;

    const createFn = async (sess) => {
      // Use document save to pass session option
      const entryDoc = new JournalEntry(doc);
      const saved = await entryDoc.save({ session: sess });

      // Update account balances for each line (atomic when session provided)
      try {
        for (const line of lines) {
          const deltaDebit = coerceAmount(line.debit);
          const deltaCredit = coerceAmount(line.credit);
          // adjust will upsert and increment debit/credit
          await AccountBalance.adjust(doc.company, line.accountCode, deltaDebit, deltaCredit, { session: sess });
        }
      } catch (balErr) {
        // Re-throw so transaction can abort when using withTransaction
        throw balErr;
      }

      // ── Tax Transaction Capture ─────────────────────────────────────
      // Automatically create TaxTransaction records for any tax-relevant journal lines.
      // This runs after account balance updates but does NOT block entry creation on failure.
      try {
        await TaxTransactionService.processJournalEntry(saved, {
          companyId: doc.company,
          userId: doc.createdBy,
          sourceType: doc.sourceType,
          sourceId: doc.sourceId,
          sourceReference: doc.sourceReference,
          sourceData: options.sourceData || {},
          session: sess
        });
      } catch (taxErr) {
        console.error('Failed to create tax transactions for journal entry:', taxErr.message);
        // Don't throw - tax transaction creation failure shouldn't block journal entry creation
      }

      await bankTransactionService.createFromJournalEntry(saved, {
        companyId: doc.company,
        userId: doc.createdBy,
        sourceType: doc.sourceType,
        sourceId: doc.sourceId,
        sourceReference: doc.sourceReference,
        sourceData: options.sourceData || {},
        bankAccountId: options.bankAccountId || options.sourceData?.bankAccountId || null,
        session: sess
      });

      // If no session provided (non-transactional create), invalidate caches (best-effort)
      if (!sess) {
        try {
          await cacheService.bumpCompanyFinancialCaches(doc.company);
        } catch (e) {
          console.error('Failed to invalidate caches after createEntry', e);
        }
        
        // Per spec 3.3: Invalidate bank account cache when journal entries are posted
        // Per spec Module 4: Invalidate petty cash cache when journal entries are posted
        // Get unique account codes from the lines
        const accountCodes = [...new Set(lines.map(l => l.accountCode))];
        for (const accountCode of accountCodes) {
          try {
            await BankAccount.invalidateCacheForLedgerAccount(doc.company, accountCode);
          } catch (e) {
            console.error('Failed to invalidate bank account cache', e);
          }
          
          // Per spec Module 4: Invalidate petty cash cache for 1050 and 1110 series accounts
          if (accountCode.startsWith('1050') || accountCode.startsWith('1110')) {
            try {
              await PettyCashFloat.invalidateCacheForLedgerAccount(doc.company, accountCode);
            } catch (e) {
              console.error('Failed to invalidate petty cash cache', e);
            }
          }
        }
      }

      return saved;
    };

    // Coerce Decimal128 fields on returned entries to plain JS numbers for callers/tests
    function coerceSavedEntry(entry) {
      if (!entry) return entry;
      try {
        const target = entry._doc || entry;
        if (target.totalDebit !== undefined && target.totalDebit != null) {
          try { target.totalDebit = Number(target.totalDebit.toString()); } catch (e) {}
        }
        if (target.totalCredit !== undefined && target.totalCredit != null) {
          try { target.totalCredit = Number(target.totalCredit.toString()); } catch (e) {}
        }
        if (Array.isArray(target.lines)) {
          target.lines.forEach(l => {
            if (l.debit !== undefined && l.debit != null) {
              try { l.debit = Number(l.debit.toString()); } catch (e) {}
            }
            if (l.credit !== undefined && l.credit != null) {
              try { l.credit = Number(l.credit.toString()); } catch (e) {}
            }
          });
        }
      } catch (e) {}
      return entry;
    }

    // If caller provided a session, use it (caller manages transaction)
    if (session) {
      try {
        const entry = await createFn(session);
        return coerceSavedEntry(entry);
      } catch (err) {
        if (err && err.code === 11000 && sourceType && sourceId) {
          const existing = await JournalEntry.findOne({ company: companyId, sourceType, sourceId });
          if (existing) return existing;
        }
        const enhanced = new Error(`JournalService.createEntry failed: ${err.message}`);
        enhanced.cause = err;
        throw enhanced;
      }
    }

    // No session provided - attempt to start a session and run a transaction if supported
    // If running under test environment (in-memory Mongo) or caller requested no transactions, avoid transactions
    if (process.env.NODE_ENV === 'test' || options.forceNoTransaction) {
      try {
        const entry = await createFn(null);
        return coerceSavedEntry(entry);
      } catch (err) {
        const enhanced = new Error(`JournalService.createEntry failed: ${err.message}`);
        enhanced.cause = err;
        throw enhanced;
      }
    }

    let sessionStarted = null;
    try {
      sessionStarted = await mongoose.startSession();
      let resultEntry = null;

      await sessionStarted.withTransaction(async (trxSession) => {
        try {
          resultEntry = await createFn(trxSession);
        } catch (err) {
          // If duplicate key error, attempt to find existing and return it (abort will be handled by withTransaction)
          if (err && err.code === 11000 && sourceType && sourceId) {
            const existing = await JournalEntry.findOne({ company: companyId, sourceType, sourceId }).session(trxSession);
            if (existing) {
              resultEntry = existing;
              return;
            }
          }
          throw err;
        }
      });

      return coerceSavedEntry(resultEntry);
    } catch (err) {
      // If transactions not supported or any other error, fallback to non-transactional create
      if (sessionStarted) sessionStarted.endSession();

      try {
        const entry = await createFn(null);
        return coerceSavedEntry(entry);
      } catch (err2) {
        if (err2 && err2.code === 11000 && sourceType && sourceId) {
          const existing = await JournalEntry.findOne({ company: companyId, sourceType, sourceId });
          if (existing) return existing;
        }
        const enhanced = new Error(`JournalService.createEntry failed: ${err2.message}`);
        enhanced.cause = err2;
        throw enhanced;
      }
    } finally {
      if (sessionStarted) sessionStarted.endSession();
    }
  }

  /**
   * Add a single debit line
   */
  
  /**
   * Create multiple journal entries atomically in a single transaction.
   * Accepts an array of entry options (same shape as createEntry options).
   * Returns an array of created/returned entries.
   */
  static async createEntriesAtomic(companyId, userId, entries = [], options = {}) {
    if (!Array.isArray(entries) || entries.length === 0) return [];

    // Normalize and validate companyId/userId
    if (userId && typeof userId === 'object' && userId._id) userId = userId._id;
    if (!companyId) throw new Error('Missing companyId when creating journal entries');
    if (!userId) throw new Error('Missing userId when creating journal entries');

    // Use provided session if caller wants to manage transaction externally
    const externalSession = options.session || null;

    const runWithSession = async (sess) => {
      const results = [];
      // Debug: log entries to be created
      try {
        console.log('JournalService.createEntriesAtomic - creating entries count:', entries.length);
      } catch (e) {}
      for (const entOpts of entries) {
        // Ensure the session is passed through to createEntry so all work uses same transaction
        // Allow duplicates when creating multiple entries atomically so
        // creators can intentionally persist multiple balanced entries
        // for the same source (tests expect two journal docs for some flows).
        const mergedOpts = Object.assign({}, entOpts, { session: sess, allowDuplicate: true, forceNoTransaction: !sess });
        try {
          const res = await this.createEntry(companyId, userId, mergedOpts);
          results.push(res);
        } catch (err) {
          console.error('JournalService.createEntriesAtomic - createEntry failed for opts:', entOpts, 'error:', err && err.message);
          throw err;
        }
      }

      // Debug: log created entries (references) for tracing in tests
      try {
        // Do not emit verbose logs in tests/CI; keep this block silent.
      } catch (e) {}

      // Invalidate cache once for the company after successful creation
      if (!sess) {
        try {
          await cacheService.bumpCompanyFinancialCaches(companyId);
        } catch (e) {}
      }

      return results;
    };

    if (externalSession) {
      return runWithSession(externalSession);
    }

    // If running tests, skip starting sessions (mongodb-memory-server not a replica set)
    if (process.env.NODE_ENV === 'test') {
      try {
        const created = await runWithSession(null);
        return created;
      } catch (err) {
        throw err;
      }
    }

    let sessionStarted = null;
    try {
      sessionStarted = await mongoose.startSession();
      let created = null;
      await sessionStarted.withTransaction(async (trx) => {
        created = await runWithSession(trx);
      });
      return created || [];
    } catch (err) {
      // Fallback to non-transactional creation if transactions unsupported
      if (sessionStarted) sessionStarted.endSession();
      try {
        const created = await runWithSession(null);
        return created;
      } finally {
        if (sessionStarted) sessionStarted.endSession();
      }
    } finally {
      if (sessionStarted) sessionStarted.endSession();
    }
  }

  static createDebitLine(accountCode, amount, description = '', reference = '') {
    const account = getAccount(accountCode);
    return {
      accountCode,
      accountName: account?.name || 'Unknown Account',
      description,
      debit: amount || 0,
      credit: 0,
      reference
    };
  }

  /**
   * Add a single credit line
   */
  static createCreditLine(accountCode, amount, description = '', reference = '') {
    const account = getAccount(accountCode);
    return {
      accountCode,
      accountName: account?.name || 'Unknown Account',
      description,
      debit: 0,
      credit: amount || 0,
      reference
    };
  }

  // =====================================================
  // SALES TRANSACTIONS
  // =====================================================

  /**
   * Invoice created (on credit)
   * Debit: Accounts Receivable
   * Credit: Sales Revenue + VAT
   */
  static async createInvoiceEntry(companyId, userId, invoice, options = {}) {
    const lines = [];
    const total = invoice.total || 0;
    const vatAmount = invoice.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Accounts Receivable
    const arAccount = await this.getMappedAccountCode(companyId, 'sales', 'accountsReceivable', DEFAULT_ACCOUNTS.accountsReceivable);
    lines.push(this.createDebitLine(
      arAccount,
      total,
      `Invoice ${invoice.invoiceNumber} - Receivable`
    ));

    // Credit: Sales Revenue
    if (subtotal > 0) {
      const salesAcct = await this.getMappedAccountCode(companyId, 'sales', 'salesRevenue', DEFAULT_ACCOUNTS.salesRevenue);
      lines.push(this.createCreditLine(
        salesAcct,
        subtotal,
        `Invoice ${invoice.invoiceNumber} - Revenue`
      ));
    }

    // Credit: VAT Output
    if (vatAmount > 0) {
      const vatAcct = await this.getMappedAccountCode(companyId, 'tax', 'vatOutput', DEFAULT_ACCOUNTS.vatOutput);
      lines.push(this.createCreditLine(
        vatAcct,
        vatAmount,
        `Invoice ${invoice.invoiceNumber} - VAT`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: invoice.date || new Date(),
      description: `Invoice ${invoice.invoiceNumber} created`,
      sourceType: 'invoice',
      sourceId: invoice._id,
      sourceReference: invoice.invoiceNumber,
      lines,
      isAutoGenerated: true,
      sourceData: {
        vatAmount,
        netAmount: subtotal,
        grossAmount: total,
        taxRate: invoice.taxRate || 0,
        taxCode: invoice.taxCode || null,
        taxRateId: invoice.taxRateId || null
      }
    }, { session: options.session });
  }

  // Backwards-compatible alias used by some controllers/tests
  static async createSalesRevenueEntry(companyId, userId, invoice, options = {}) {
    return this.createInvoiceEntry(companyId, userId, invoice, options);
  }

  /**
   * Create COGS journal entry for a sale (single aggregated entry)
   * Debit: Cost of Goods Sold
   * Credit: Inventory
   * options may include { session }
   */
  static async createSaleCOGSEntry(companyId, userId, payload, options = {}) {
    const { invoiceId, invoiceNumber, date, totalCost = 0 } = payload;
    const lines = [];

    if (!totalCost || totalCost <= 0) {
      // nothing to record
      return null;
    }

    // Debit: Cost of Goods Sold
    const cogsAcct = await this.getMappedAccountCode(companyId, 'inventory', 'costOfGoodsSold', DEFAULT_ACCOUNTS.costOfGoodsSold);
    lines.push(this.createDebitLine(
      cogsAcct,
      totalCost,
      `COGS for Invoice ${invoiceNumber}`
    ));

    // Credit: Inventory
    const invAcct = await this.getMappedAccountCode(companyId, 'purchases', 'inventory', DEFAULT_ACCOUNTS.inventory);
    lines.push(this.createCreditLine(
      invAcct,
      totalCost,
      `Inventory reduction for Invoice ${invoiceNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: date || new Date(),
      description: `COGS for ${invoiceNumber}`,
      sourceType: 'cogs',
      sourceId: invoiceId,
      sourceReference: invoiceNumber,
      lines,
      isAutoGenerated: true,
      session: options.session
    });
  }

  // Backwards-compatible alias used by controllers/tests
  static async createCOGSEntry(companyId, userId, payload, options = {}) {
    return this.createSaleCOGSEntry(companyId, userId, payload, options);
  }

  /**
   * Invoice paid (cash received)
   * Debit: Cash/Bank
   * Credit: Accounts Receivable
   */
  static async createInvoicePaymentEntry(companyId, userId, payment) {
    const lines = [];

    // Determine cash account based on payment method
    let cashAccount;
    const paymentMethod = payment.paymentMethod;
    
    if (paymentMethod === 'bank_transfer' || paymentMethod === 'cheque') {
      // Use the bank account code if provided, otherwise default to cash at bank
      cashAccount = payment.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (paymentMethod === 'mobile_money') {
      // Use the momo account code if provided, otherwise default to mtn momo
      cashAccount = payment.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo;
    } else if (paymentMethod === 'bank') {
      cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
    } else {
      // cash, credit, or any other method
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    }

    // Debit: Cash/Bank
    lines.push(this.createDebitLine(
      cashAccount,
      payment.amount,
      `Payment for ${payment.invoiceNumber}`
    ));

    // Credit: Accounts Receivable
    const arAccount = await this.getMappedAccountCode(companyId, 'sales', 'accountsReceivable', DEFAULT_ACCOUNTS.accountsReceivable);
    lines.push(this.createCreditLine(
      arAccount,
      payment.amount,
      `Payment for ${payment.invoiceNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description: `Payment received for invoice ${payment.invoiceNumber}`,
      sourceType: 'payment',
      sourceReference: payment.invoiceNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Credit Note issued (customer returns goods)
   *
   * For sales return with refund (money returned to customer):
   *   Debit: Sales Returns (4100)
   *   Debit: VAT Output (2220)
   *   Credit: Cash/Bank (based on refund method)
   *
   * For inventory return:
   *   Debit: Inventory (1400)
   *   Credit: Cost of Goods Sold (5000)
   *
   * For sales return without immediate refund (reduce AR):
   *   Debit: Sales Returns (4100)
   *   Debit: VAT Output (2220)
   *   Credit: Accounts Receivable (1300)
   */
  static async createCreditNoteEntry(companyId, userId, creditNote) {
    const lines = [];
    const total = creditNote.total || 0;
    const vatAmount = creditNote.vatAmount || 0;
    const subtotal = total - vatAmount;
    
    // Determine refund method: 'bank', 'cash', or 'ar' (default to AR for credit)
    const refundMethod = creditNote.refundMethod || 'ar';
    const inventoryCost = creditNote.inventoryCost || 0;
    
    // Determine cash account based on refund method
    let cashAccount;
    if (refundMethod === 'bank_transfer' || refundMethod === 'cheque') {
      cashAccount = creditNote.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (refundMethod === 'mobile_money') {
      cashAccount = creditNote.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo;
    } else if (refundMethod === 'bank') {
      cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
    } else if (refundMethod === 'cash') {
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    } else {
      // Default to AR (no immediate refund)
      cashAccount = null;
    }

    // Debit: Sales Returns
    if (subtotal > 0) {
      const salesReturnsAcct = await this.getMappedAccountCode(companyId, 'sales', 'salesReturns', DEFAULT_ACCOUNTS.salesReturns);
      lines.push(this.createDebitLine(
        salesReturnsAcct,
        subtotal,
        `Credit Note ${creditNote.creditNoteNumber} - Returns`
      ));
    }

    // Debit: VAT Output (reduction of output VAT on credit note)
    if (vatAmount > 0) {
      const vatAcct = await this.getMappedAccountCode(companyId, 'tax', 'vatOutput', DEFAULT_ACCOUNTS.vatOutput);
      lines.push(this.createDebitLine(
        vatAcct,
        vatAmount,
        `Credit Note ${creditNote.creditNoteNumber} - VAT`
      ));
    }

    // Credit: Either Cash/Bank (refund) or Accounts Receivable (credit)
    if (cashAccount) {
      // Refund via cash/bank
      lines.push(this.createCreditLine(
        cashAccount,
        total,
        `Credit Note ${creditNote.creditNoteNumber} - Refund`
      ));
    } else {
      // No immediate refund - reduce AR instead
      const arAccount = await this.getMappedAccountCode(companyId, 'sales', 'accountsReceivable', DEFAULT_ACCOUNTS.accountsReceivable);
      lines.push(this.createCreditLine(
        arAccount,
        total,
        `Credit Note ${creditNote.creditNoteNumber}`
      ));
    }

    // Add inventory/COGS entries if there's inventory cost (stock returned)
    if (inventoryCost > 0) {
      // Debit: Inventory (stock returning to warehouse)
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.inventory,
        inventoryCost,
        `Credit Note ${creditNote.creditNoteNumber} - Inventory Return`
      ));

      // Credit: Cost of Goods Sold (reverse the COGS)
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.costOfGoodsSold,
        inventoryCost,
        `Credit Note ${creditNote.creditNoteNumber} - COGS Reversal`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: creditNote.date || new Date(),
      description: `Credit Note ${creditNote.creditNoteNumber} issued`,
      sourceType: 'credit_note',
      sourceId: creditNote._id,
      sourceReference: creditNote.creditNoteNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PURCHASE TRANSACTIONS
  // =====================================================

  /**
   * Purchase received (on credit)
   * Debit: Inventory + VAT
   * Credit: Accounts Payable
   */
  static async createPurchaseEntry(companyId, userId, purchase, options = {}) {
    const lines = [];
    const total = purchase.total || 0;
    const vatAmount = purchase.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Inventory
    if (subtotal > 0) {
      const invAcct = await this.getMappedAccountCode(companyId, 'purchases', 'inventory', DEFAULT_ACCOUNTS.inventory);
      lines.push(this.createDebitLine(
        invAcct,
        subtotal,
        `Purchase ${purchase.purchaseNumber} - Inventory`
      ));
    }

    // Debit: VAT Input (2210) — input tax claimable from RRA
    if (vatAmount > 0) {
      const vatInputAcct = await this.getMappedAccountCode(companyId, 'tax', 'vatInput', DEFAULT_ACCOUNTS.vatInput);
      lines.push(this.createDebitLine(
        vatInputAcct,
        vatAmount,
        `Purchase ${purchase.purchaseNumber} - VAT`
      ));
    }

    // Credit: Accounts Payable
    const apAcct = await this.getMappedAccountCode(companyId, 'purchases', 'accountsPayable', DEFAULT_ACCOUNTS.accountsPayable);
    lines.push(this.createCreditLine(
      apAcct,
      total,
      `Purchase ${purchase.purchaseNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: purchase.date || new Date(),
      description: `Purchase ${purchase.purchaseNumber} received`,
      sourceType: 'purchase',
      sourceId: purchase._id,
      sourceReference: purchase.purchaseNumber,
      lines,
      isAutoGenerated: true,
      sourceData: {
        vatAmount,
        netAmount: subtotal,
        grossAmount: total,
        taxRate: purchase.taxRate || 0,
        taxCode: purchase.taxCode || null,
        taxRateId: purchase.taxRateId || null
      }
    }, { session: options.session });
  }

  /**
   * Purchase paid (cash paid)
   * Debit: Accounts Payable
   * Credit: Cash/Bank
   */
  static async createPurchasePaymentEntry(companyId, userId, payment) {
    const lines = [];

    // Determine cash account based on payment method
    let cashAccount;
    const paymentMethod = payment.paymentMethod;
    
    if (paymentMethod === 'bank_transfer' || paymentMethod === 'cheque') {
      // Use the bank account code if provided, otherwise default to cash at bank
      cashAccount = payment.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (paymentMethod === 'mobile_money') {
      // Use the momo account code if provided, otherwise default to mtn momo
      cashAccount = payment.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo;
    } else if (paymentMethod === 'bank') {
      cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
    } else {
      // cash, credit, or any other method
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    }

    // Build description with VAT info if available
    let description = `Payment made for purchase ${payment.purchaseNumber}`;
    if (payment.vatAmount > 0 && payment.netAmount > 0) {
      description += ` (Net: ${payment.netAmount.toLocaleString()}, VAT: ${payment.vatAmount.toLocaleString()})`;
    } else if (payment.vatAmount > 0) {
      description += ` (includes VAT: ${payment.vatAmount.toLocaleString()})`;
    }

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      await this.getMappedAccountCode(companyId, 'purchases', 'accountsPayable', DEFAULT_ACCOUNTS.accountsPayable),
      payment.amount,
      description
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      payment.amount,
      description
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description,
      sourceType: 'payment',
      sourceReference: payment.purchaseNumber,
      lines,
      isAutoGenerated: true,
      sourceData: {
        vatAmount: payment.vatAmount || 0,
        netAmount: payment.netAmount || payment.amount,
        grossAmount: payment.amount
      }
    });
  }

  // =====================================================
  // EXPENSE TRANSACTIONS
  // =====================================================

  /**
   * Expense paid immediately
   * Debit: Expense Account (amount excluding VAT)
   * Debit: VAT Receivable / VAT Input (tax amount) — if vatAmount > 0
   * Credit: Cash/Bank (total including VAT)
   */
  static async createExpenseEntry(companyId, userId, expense) {
    const lines = [];
    const totalAmount = expense.amount || 0;
    const vatAmount = expense.vatAmount || 0;
    const whtAmount = expense.withholdingTax || 0;
    
    // Net expense amount (excluding VAT)
    const netAmount = totalAmount - vatAmount;

    // Determine expense account - use provided account code or fall back to category mapping
    let expenseAccount = expense.expenseAccountCode;
    if (!expenseAccount && expense.category) {
      expenseAccount = DEFAULT_ACCOUNTS[expense.category] || DEFAULT_ACCOUNTS.otherExpenses;
    }
    if (!expenseAccount) {
      expenseAccount = DEFAULT_ACCOUNTS.otherExpenses;
    }

    // Determine cash account based on payment method
    let cashAccount;
    const paymentMethod = expense.paymentMethod;
    
    if (paymentMethod === 'bank_transfer' || paymentMethod === 'cheque' || paymentMethod === 'bank' || paymentMethod === 'credit_card') {
      cashAccount = expense.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (paymentMethod === 'mobile_money') {
      cashAccount = expense.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (paymentMethod === 'cash') {
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    } else if (paymentMethod === 'petty_cash') {
      cashAccount = DEFAULT_ACCOUNTS.pettyCash || DEFAULT_ACCOUNTS.cashInHand;
    } else if (paymentMethod === 'payable') {
      cashAccount = DEFAULT_ACCOUNTS.accountsPayable;
    } else {
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    }

    // Debit: Expense (net amount excluding VAT)
    if (netAmount > 0) {
      lines.push(this.createDebitLine(
        expenseAccount,
        netAmount,
        expense.description || 'Expense'
      ));
    }

    // Debit: VAT Input (2210) — input tax on expenses
    if (vatAmount > 0) {
      const vatAccount = await this.getMappedAccountCode(companyId, 'tax', 'vatInput', DEFAULT_ACCOUNTS.vatInput);
      lines.push(this.createDebitLine(
        vatAccount,
        vatAmount,
        `${expense.description || 'Expense'} - VAT Input`
      ));
    }

    // Credit: Withholding Tax Payable (2500) — if WHT applies
    if (whtAmount > 0) {
      const whtAccount = await this.getMappedAccountCode(companyId, 'tax', 'withholdingTaxPayable', DEFAULT_ACCOUNTS.withholdingTaxPayable);
      lines.push(this.createCreditLine(
        whtAccount,
        whtAmount,
        `${expense.description || 'Expense'} - WHT withheld`
      ));
    }

    // Credit: Cash/Bank (total amount including VAT, minus WHT withheld)
    const totalCredit = netAmount + vatAmount - whtAmount;
    if (totalCredit > 0) {
      lines.push(this.createCreditLine(
        cashAccount,
        totalCredit,
        expense.description || 'Expense payment'
      ));
    }

    return this.createEntry(companyId, userId, {
      date: expense.date || new Date(),
      description: expense.description || 'Expense payment',
      sourceType: 'expense',
      sourceId: expense._id,
      lines,
      isAutoGenerated: true,
      sourceData: {
        vatAmount,
        netAmount,
        grossAmount: totalAmount,
        taxRate: expense.taxRate || 0,
        taxCode: expense.taxCode || null,
        taxRateId: expense.taxRateId || null
      }
    });
  }

  // =====================================================
  // ASSET TRANSACTIONS
  // =====================================================

  /**
   * Asset purchased (cash or credit)
   * Debit: Fixed Asset (cost excluding VAT)
   * Debit: VAT Receivable / Input VAT (tax amount) — if vatAmount > 0
   * Credit: Cash/Bank or Accounts Payable (total including VAT)
   */
  static async createAssetPurchaseEntry(companyId, userId, asset) {
    const lines = [];
    const totalCost = asset.purchaseCost || 0;
    const vatAmount = asset.vatAmount || 0;
    const netCost = totalCost - vatAmount;
    const purchaseType = asset.purchaseType || 'cash'; // 'cash' or 'credit'

    // Determine asset account based on category
    const assetAccountCode = this.getAssetAccountCode(asset.category);

    // Debit: Fixed Asset (cost excluding VAT)
    if (netCost > 0) {
      lines.push(this.createDebitLine(
        assetAccountCode,
        netCost,
        `Asset: ${asset.name}`
      ));
    }

    // Debit: VAT Input (2210) — input tax on asset purchases
    if (vatAmount > 0) {
      const vatAccount = await this.getMappedAccountCode(companyId, 'tax', 'vatInput', DEFAULT_ACCOUNTS.vatInput);
      lines.push(this.createDebitLine(
        vatAccount,
        vatAmount,
        `Asset: ${asset.name} - VAT Input`
      ));
    }

    // Credit: Cash/Bank or Accounts Payable
    if (purchaseType === 'credit') {
      // Credit: Accounts Payable
      const apAccount = await this.getMappedAccountCode(companyId, 'purchases', 'accountsPayable', DEFAULT_ACCOUNTS.accountsPayable);
      lines.push(this.createCreditLine(
        apAccount,
        totalCost,
        `Asset purchase: ${asset.name}`
      ));
    } else {
      // Determine cash account based on payment method
      let cashAccount;
      const paymentMethod = asset.paymentMethod;
      
      if (paymentMethod === 'bank_transfer' || paymentMethod === 'cheque') {
        cashAccount = asset.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
      } else if (paymentMethod === 'mobile_money') {
        cashAccount = asset.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo;
      } else if (paymentMethod === 'bank') {
        cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
      } else {
        cashAccount = DEFAULT_ACCOUNTS.cashInHand;
      }

      // Credit: Cash/Bank
      lines.push(this.createCreditLine(
        cashAccount,
        totalCost,
        `Asset purchase: ${asset.name}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: asset.purchaseDate || new Date(),
      description: `Asset purchased: ${asset.name}`,
      sourceType: 'asset',
      sourceId: asset._id,
      sourceReference: asset.assetCode,
      lines,
      isAutoGenerated: true,
      sourceData: {
        vatAmount,
        netAmount: netCost,
        grossAmount: totalCost,
        taxRate: asset.taxRate || 0,
        taxCode: asset.taxCode || null,
        taxRateId: asset.taxRateId || null
      }
    });
  }

  /**
   * Monthly Depreciation
   * Debit: Depreciation Expense
   * Credit: Accumulated Depreciation
   */
  static async createDepreciationEntry(companyId, userId, depreciation) {
    const lines = [];
    const accumulatedDepreciationAccount =
      depreciation.accumulatedDepreciationAccount ||
      depreciation.accumulatedDepreciationAccountCode ||
      DEFAULT_ACCOUNTS.accumulatedDepreciationOther;

    // Debit: Depreciation Expense
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.depreciation,
      depreciation.amount,
      `Depreciation for ${depreciation.period}`
    ));

    // Credit: Accumulated Depreciation
    lines.push(this.createCreditLine(
      accumulatedDepreciationAccount,
      depreciation.amount,
      `Depreciation for ${depreciation.period}`
    ));

    return this.createEntry(companyId, userId, {
      date: depreciation.date || new Date(),
      description: `Depreciation expense - ${depreciation.period}`,
      sourceType: 'depreciation',
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Asset Disposal
   * Entry depends on whether there's gain or loss
   * 
   * If Gain (Proceeds > NBV):
   *   Debit: Cash/Bank (proceeds)
   *   Debit: Accumulated Depreciation (NBV)
   *   Credit: Fixed Asset (cost)
   *   Credit: Gain on Disposal
   * 
   * If Loss (NBV > Proceeds):
   *   Debit: Cash/Bank (proceeds)
   *   Debit: Accumulated Depreciation
   *   Debit: Loss on Disposal
   *   Credit: Fixed Asset (cost)
   */
  static async createAssetDisposalEntry(companyId, userId, asset) {
    const lines = [];

    const cost = asset.purchaseCost || 0;
    const accumulatedDep = asset.accumulatedDepreciation || 0;
    const proceeds = asset.disposalAmount || 0;
    const netBookValue = cost - accumulatedDep;
    const gainLoss = proceeds - netBookValue;

    // Determine cash account
    let cashAccount;
    const paymentMethod = asset.paymentMethod;
    
    if (paymentMethod === 'bank_transfer' || paymentMethod === 'cheque') {
      cashAccount = asset.bankAccountCode || DEFAULT_ACCOUNTS.cashAtBank;
    } else if (paymentMethod === 'mobile_money') {
      cashAccount = asset.bankAccountCode || DEFAULT_ACCOUNTS.mtnMoMo;
    } else if (paymentMethod === 'bank') {
      cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
    } else {
      cashAccount = DEFAULT_ACCOUNTS.cashInHand;
    }

    // Determine asset account
    const assetAccountCode = this.getAssetAccountCode(asset.category);

    // Debit: Cash/Bank (proceeds)
    if (proceeds > 0) {
      lines.push(this.createDebitLine(
        cashAccount,
        proceeds,
        `Asset disposal proceeds: ${asset.name}`
      ));
    }

    // Debit: Accumulated Depreciation
    if (accumulatedDep > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.accumulatedDepreciation,
        accumulatedDep,
        `Remove accumulated depreciation: ${asset.name}`
      ));
    }

    // Credit: Fixed Asset (original cost)
    lines.push(this.createCreditLine(
      assetAccountCode,
      cost,
      `Remove asset cost: ${asset.name}`
    ));

    // Handle Gain or Loss
    if (gainLoss > 0) {
      // Gain
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.gainOnDisposal,
        gainLoss,
        `Gain on disposal: ${asset.name}`
      ));
    } else if (gainLoss < 0) {
      // Loss
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.lossOnDisposal,
        Math.abs(gainLoss),
        `Loss on disposal: ${asset.name}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: asset.disposalDate || new Date(),
      description: `Asset disposed: ${asset.name}`,
      sourceType: 'asset',
      sourceId: asset._id,
      sourceReference: asset.assetCode,
      lines,
      isAutoGenerated: true,
      notes: `Disposal - Cost: ${cost}, Accum Dep: ${accumulatedDep}, Proceeds: ${proceeds}, Gain/Loss: ${gainLoss}`
    });
  }

  // =====================================================
  // LOAN TRANSACTIONS
  // =====================================================

  /**
   * Loan received
   * Debit: Cash/Bank
   * Credit: Loan Liability
   */
  static async createLoanReceivedEntry(companyId, userId, loan) {
    const lines = [];

    const cashAccount = loan.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    const loanAccount = loan.loanType === 'short_term'
      ? DEFAULT_ACCOUNTS.shortTermLoans
      : DEFAULT_ACCOUNTS.longTermLoans;

    // Debit: Cash/Bank
    lines.push(this.createDebitLine(
      cashAccount,
      loan.principalAmount,
      `Loan received: ${loan.loanNumber}`
    ));

    // Credit: Loan Liability
    lines.push(this.createCreditLine(
      loanAccount,
      loan.principalAmount,
      `Loan: ${loan.loanNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: loan.disbursementDate || new Date(),
      description: `Loan received: ${loan.loanNumber}`,
      sourceType: 'loan',
      sourceId: loan._id,
      sourceReference: loan.loanNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Loan payment (principal + interest)
   * Debit: Loan Liability (principal)
   * Debit: Interest Expense
   * Credit: Cash/Bank
   */
  static async createLoanPaymentEntry(companyId, userId, payment) {
    const lines = [];

    const cashAccount = payment.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    const principal = payment.principalAmount || 0;
    const interest = payment.interestAmount || 0;
    const total = principal + interest;

    // Debit: Loan Liability (principal) - use correct account based on loan term
    if (principal > 0) {
      const loanAccount = payment.loanTerm === 'long_term'
        ? DEFAULT_ACCOUNTS.longTermLoans
        : DEFAULT_ACCOUNTS.shortTermLoans;
      lines.push(this.createDebitLine(
        loanAccount,
        principal,
        `Loan payment: ${payment.loanNumber}`
      ));
    }

    // Debit: Interest Expense
    if (interest > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.interestExpense,
        interest,
        `Interest payment: ${payment.loanNumber}`
      ));
    }

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      total,
      `Loan payment: ${payment.loanNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description: `Loan payment: ${payment.loanNumber}`,
      sourceType: 'loan',
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // HELPER METHODS
  // =====================================================

  /**
   * Resolve a company-scoped account code via AccountMapping.
   * Falls back to provided fallback or DEFAULT_ACCOUNTS[key].
   */
  static async getMappedAccountCode(companyId, moduleName, key, fallback, context = {}) {
    try {
      // If context provides a warehouseId, and the mapping requested is inventory, prefer warehouse-specific inventory account
      if (context && context.warehouseId && (key === 'inventory' || key === 'inventoryAccount' || key === 'inventory_account')) {
        try {
          const Warehouse = require('../models/Warehouse');
          const wh = await Warehouse.findOne({ _id: context.warehouseId, company: companyId }).lean();
          if (wh && wh.inventoryAccount) return wh.inventoryAccount;
        } catch (e) {
          // ignore and fallback
        }
      }

      // If context provides a productId, prefer product-level account when no warehouse-specific account
      if (context && context.productId && (key === 'inventory' || key === 'inventoryAccount' || key === 'inventory_account')) {
        try {
          const Product = require('../models/Product');
          const prod = await Product.findOne({ _id: context.productId, company: companyId }).lean();
          if (prod && prod.inventoryAccount) return prod.inventoryAccount;
        } catch (e) {
          // ignore
        }
      }

      const code = await accountMappingService.resolve(companyId, moduleName, key, fallback);
      return code || fallback;
    } catch (err) {
      return fallback;
    }
  }


  /**
   * Get asset account code based on category
   */
  static getAssetAccountCode(category) {
    const categoryMap = {
      'equipment': DEFAULT_ACCOUNTS.equipment,
      'computers': DEFAULT_ACCOUNTS.computers,
      'vehicles': DEFAULT_ACCOUNTS.vehicles,
      'furniture': DEFAULT_ACCOUNTS.furniture,
      'buildings': DEFAULT_ACCOUNTS.buildings,
      'land': DEFAULT_ACCOUNTS.land,
      'machinery': DEFAULT_ACCOUNTS.machinery,
      'other': '1790'
    };
    return categoryMap[category] || DEFAULT_ACCOUNTS.equipment;
  }

  /**
   * Create manual journal entry
   */
  static async createManualEntry(companyId, userId, entryData) {
    return this.createEntry(companyId, userId, {
      ...entryData,
      sourceType: 'manual',
      isAutoGenerated: false
    });
  }

  // =====================================================
  // BANK TRANSFER
  // =====================================================

  /**
   * Bank transfer between accounts
   * Debit: Destination Bank Account
   * Credit: Source Bank Account
   */
  static async createBankTransferEntry(companyId, userId, options) {
    const {
      fromAccountCode,
      toAccountCode,
      fromAccountName,
      toAccountName,
      amount,
      description,
      referenceNumber,
      date = new Date()
    } = options;

    const lines = [];

    // Debit: Destination Bank Account (receiving money)
    lines.push(this.createDebitLine(
      toAccountCode || DEFAULT_ACCOUNTS.cashAtBank,
      amount,
      `Transfer to ${toAccountName || 'Bank Account'}`
    ));

    // Credit: Source Bank Account (sending money)
    lines.push(this.createCreditLine(
      fromAccountCode || DEFAULT_ACCOUNTS.cashAtBank,
      amount,
      `Transfer from ${fromAccountName || 'Bank Account'}`
    ));

    return this.createEntry(companyId, userId, {
      date,
      description: description || `Bank transfer`,
      sourceType: 'bank_transfer',
      sourceReference: referenceNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PURCHASE RETURN
  // =====================================================

  /**
   * Purchase return (returning goods to supplier)
   * Debit: Accounts Payable
   * Credit: Purchase Returns (contra-COGS, flows to P&L) + VAT Input reversal
   */
  static async createPurchaseReturnEntry(companyId, userId, purchaseReturn) {
    const lines = [];
    const total = purchaseReturn.total || 0;
    const vatAmount = purchaseReturn.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      total,
      `Purchase Return ${purchaseReturn.returnNumber}`
    ));

    // Credit: Purchase Returns (5200) — contra-COGS, flows to P&L
    if (subtotal > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.purchaseReturns || '5200',
        subtotal,
        `Purchase Return ${purchaseReturn.returnNumber}`
      ));
    }

    // Credit: VAT Input (2210) — reversal of input VAT on purchase return
    if (vatAmount > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.vatInput,
        vatAmount,
        `Purchase Return ${purchaseReturn.returnNumber} - VAT`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: purchaseReturn.date || new Date(),
      description: `Purchase Return ${purchaseReturn.returnNumber} approved`,
      sourceType: 'purchase_return',
      sourceId: purchaseReturn._id,
      sourceReference: purchaseReturn.returnNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Purchase return refund
   * Debit: Accounts Payable
   * Credit: Cash/Bank
   */
  static async createPurchaseReturnRefundEntry(companyId, userId, refund) {
    const lines = [];

    // Determine cash account
    const cashAccount = refund.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      refund.amount,
      `Refund for ${refund.returnNumber}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      refund.amount,
      `Refund for ${refund.returnNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: refund.date || new Date(),
      description: `Purchase Return ${refund.returnNumber} refund`,
      sourceType: 'purchase_return',
      sourceReference: refund.returnNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // STOCK ADJUSTMENT
  // =====================================================

  /**
   * Stock adjustment entry
   * Uses 7100 Stock Adjustment (Expense) for all adjustments.
   * Surplus: DR Inventory, CR 7100
   * Shortage: DR 7100, CR Inventory
   */
  static async createStockAdjustmentEntry(companyId, userId, adjustment) {
    const lines = [];
    const amount = adjustment.adjustmentAmount || 0;
    const adjustmentType = adjustment.adjustmentType; // 'increase' or 'decrease'

    // Resolve inventory account (support warehouse/product overrides)
    let inventoryAcct = DEFAULT_ACCOUNTS.inventory;
    if (adjustment.warehouseId || adjustment.productId) {
      const context = {};
      if (adjustment.warehouseId) context.warehouseId = adjustment.warehouseId;
      if (adjustment.productId) context.productId = adjustment.productId;
      try {
        inventoryAcct = await this.getMappedAccountCode(companyId, 'purchases', 'inventory', DEFAULT_ACCOUNTS.inventory, context);
      } catch (err) {
        // fallback to default
      }
    }

    if (adjustmentType === 'increase') {
      // Surplus: Debit Inventory, Credit 7100 Stock Adjustment
      lines.push(this.createDebitLine(
        inventoryAcct,
        amount,
        `Stock adjustment increase: ${adjustment.productName}`
      ));

      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.stockAdjustment || '7100',
        amount,
        `Stock adjustment increase: ${adjustment.productName}`
      ));
    } else {
      // Shortage: Debit 7100 Stock Adjustment, Credit Inventory
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.stockAdjustment || '7100',
        amount,
        `Stock adjustment decrease: ${adjustment.productName}`
      ));

      lines.push(this.createCreditLine(
        inventoryAcct,
        amount,
        `Stock adjustment decrease: ${adjustment.productName}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: adjustment.date || new Date(),
      description: `Stock adjustment: ${adjustment.productName} - ${adjustmentType}`,
      sourceType: 'stock_adjustment',
      sourceId: adjustment._id,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PAYROLL
  // =====================================================

  /**
   * Payroll payment
   * Debit: Payroll Expense
   * Credit: Cash/Bank (net pay)
   * Credit: Tax Payable (withheld tax)
   * Credit: Employee Deductions Payable
   */
  static async createPayrollEntry(companyId, userId, payroll) {
    const lines = [];

    const grossPay = payroll.grossPay || 0;
    const netPay = payroll.netPay || 0;
    const taxWithheld = payroll.taxWithheld || 0;
    const ssnWithheld = payroll.ssnWithheld || 0;
    const otherDeductions = payroll.otherDeductions || 0;

    // Determine cash account
    const cashAccount = payroll.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Payroll Expense
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.payrollExpenses || '5410',
      grossPay,
      `Payroll: ${payroll.period || 'Salary'}`
    ));

    // Credit: Cash/Bank (net pay to employee)
    if (netPay > 0) {
      lines.push(this.createCreditLine(
        cashAccount,
        netPay,
        `Net salary payment: ${payroll.period || 'Salary'}`
      ));
    }

    // Credit: Tax Payable (withheld tax)
    if (taxWithheld > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.payePayable || '2230',
        taxWithheld,
        `Tax withheld: ${payroll.period || 'Salary'}`
      ));
    }

    // Credit: RSSB Payable (social security)
    if (ssnWithheld > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.rssbPayable || '2240',
        ssnWithheld,
        `RSSB contribution: ${payroll.period || 'Salary'}`
      ));
    }

    // Employer contribution
    const employerContribution = payroll.employerContribution || 0;
    if (employerContribution > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.rssbEmployerCost || '6150',
        employerContribution,
        `Employer contribution: ${payroll.period || 'Salary'}`
      ));
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.employerContributionPayable || '2310',
        employerContribution,
        `Employer contribution payable: ${payroll.period || 'Salary'}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: payroll.paymentDate || new Date(),
      description: `Payroll: ${payroll.period || 'Salary'} - ${payroll.employeeName}`,
      sourceType: 'payroll',
      sourceId: payroll._id,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // TAX PAYMENT
  // =====================================================

  /**
   * Tax payment
   * Debit: Tax Payable
   * Credit: Cash/Bank
   */
  static async createTaxPaymentEntry(companyId, userId, taxPayment) {
    const lines = [];
    const amount = taxPayment.amount || 0;

    // Determine cash account
    const cashAccount = taxPayment.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Tax Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.vatOutput || '2220',
      amount,
      `Tax payment: ${taxPayment.taxType || 'VAT'}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      amount,
      `Tax payment: ${taxPayment.taxType || 'VAT'}`
    ));

    return this.createEntry(companyId, userId, {
      date: taxPayment.paymentDate || new Date(),
      description: `Tax payment: ${taxPayment.taxType || 'VAT'}`,
      sourceType: 'tax_payment',
      sourceId: taxPayment._id,
      lines,
      isAutoGenerated: true
    });
  }
}

module.exports = JournalService;
