const mongoose = require('mongoose');
const Liability = require('../models/Liability');
const JournalEntry = require('../models/JournalEntry');
const ChartOfAccount = require('../models/ChartOfAccount');
const { BankAccount } = require('../models/BankAccount');
const { nextSequence } = require('./sequenceService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');
const PeriodService = require('./periodService');

class LiabilityService {
  
  // ── CREATE LIABILITY + POST DRAWDOWN JOURNAL ──────────────────────
  static async create(companyId, data, userId) {
    // Validate accounts belong to this company
    const liabilityAccount = await ChartOfAccount.findOne({ 
      _id: data.liabilityAccountId, 
      company: companyId 
    });
    if (!liabilityAccount) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    if (data.interestExpenseAccountId) {
      const interestAccount = await ChartOfAccount.findOne({ 
        _id: data.interestExpenseAccountId, 
        company: companyId 
      });
      if (!interestAccount) {
        const error = new Error('NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }
    }

    // Validate bank account if provided
    let bankAccount = null;
    if (data.bankAccountId) {
      bankAccount = await BankAccount.findOne({ 
        _id: data.bankAccountId, 
        company: companyId 
      });
      if (!bankAccount) {
        const error = new Error('NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }
    }

    try {
      // Create liability
      const liability = await Liability.create({
        company_id: companyId,
        name: data.name,
        type: data.type,
        lenderName: data.lenderName || null,
        principalAmount: data.principalAmount,
        outstandingBalance: data.principalAmount,
        interestRatePct: data.interestRatePct || null,
        interestMethod: data.interestMethod || 'simple',
        durationMonths: data.durationMonths || null,
        liabilityAccountId: data.liabilityAccountId,
        interestExpenseAccountId: data.interestExpenseAccountId || null,
        startDate: data.startDate,
        endDate: data.endDate || null,
        status: 'active',
        notes: data.notes || null,
        createdBy: userId
      });

      const createdLiability = liability;

      // ── CREATE JOURNAL ENTRY FOR LIABILITY ─────────────────────────────
      // Always create journal entry for liability drawdown (DR Bank / CR Liability)
      // even if no bank account provided (use default bank account code)
      let journalEntryId = null;
      if (data.principalAmount > 0) {
        const entryDate = data.startDate || new Date();
        const entryNumber = await JournalEntry.generateEntryNumber(companyId);
        const period = await PeriodService.getOpenPeriodId(companyId, entryDate);

        // Get bank account code (from bank account or use default)
        const bankLedgerCode = bankAccount?.ledgerAccountId?.code || '1100';
        const bankName = bankAccount?.name || 'Cash at Bank';

        const journalEntry = await JournalEntry.create({
          company: companyId,
          entryNumber,
          date: entryDate,
          description: `Liability Created - ${createdLiability.name} - ${createdLiability.reference_no}`,
          sourceType: 'liability_drawdown',
          sourceId: createdLiability._id.toString(),
          reference: createdLiability.reference_no,
          status: 'posted',
          lines: [
            {
              accountCode: bankLedgerCode,
              accountName: bankName,
              description: 'Liability proceeds received',
              debit: data.principalAmount,
              credit: 0
            },
            {
              accountCode: liabilityAccount.code,
              accountName: liabilityAccount.name,
              description: 'Liability recognized',
              debit: 0,
              credit: data.principalAmount
            }
          ],
          totalDebit: data.principalAmount,
          totalCredit: data.principalAmount,
          debitTotal: data.principalAmount,
          creditTotal: data.principalAmount,
          postedBy: userId,
          createdBy: userId,
          period: period,
          isAutoGenerated: true
        });

        journalEntryId = journalEntry._id;

        // Create BankTransaction if bank account provided
        if (bankAccount) {
          try {
            await bankAccount.addTransaction({
              type: 'deposit',
              amount: data.principalAmount,
              description: `Liability funding: ${createdLiability.name} (${createdLiability.reference_no})`,
              date: entryDate,
              referenceNumber: createdLiability.reference_no,
              referenceType: 'Liability',
              reference: createdLiability._id,
              createdBy: userId,
              journalEntryId: journalEntry._id
            });
            bankAccount.cacheValid = false;
            await bankAccount.save();
          } catch (btErr) {
            console.error('BankTransaction creation failed for liability:', btErr.message);
          }
        }

        // Add drawdown transaction
        createdLiability.transactions.push({
          transactionDate: entryDate,
          type: 'drawdown',
          amount: data.principalAmount,
          principalPortion: data.principalAmount,
          interestPortion: 0,
          bankAccountId: bankAccount?._id || null,
          journalEntryId: journalEntryId,
          notes: 'Initial drawdown'
        });
      }

      // Update liability with journal entry ID
      await Liability.findByIdAndUpdate(createdLiability._id, {
        journalEntryId: journalEntryId
      });
      
      // Reload to get final data
      const finalLiability = await Liability.findById(createdLiability._id);
      return finalLiability;

    } catch (err) {
      throw err;
    }
  }

  // ── POST REPAYMENT ─────────────────────────────────────────────────
  static async postRepayment(companyId, liabilityId, data, userId) {
    const liability = await Liability.findOne({ _id: liabilityId, company_id: companyId });

    if (!liability) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    if (liability.status !== 'active') {
      throw new Error('Liability is not active');
    }

    const { principalPortion, interestPortion = 0, paymentDate, bankAccountId } = data;
    const totalPayment = principalPortion + interestPortion;

    if (principalPortion > liability.outstandingBalance) {
      const error = new Error('REPAYMENT_EXCEEDS_OUTSTANDING');
      error.statusCode = 400;
      throw error;
    }

    // Validate bank account
    const bankAccount = await BankAccount.findOne({ 
      _id: bankAccountId, 
      company: companyId 
    });
    if (!bankAccount) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    // Validate liability account
    const liabilityAccount = await ChartOfAccount.findOne({ 
      _id: liability.liabilityAccountId, 
      company: companyId 
    });
    if (!liabilityAccount) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    try {
      const entryDate = paymentDate ? new Date(paymentDate) : new Date();
      const entryNumber = await JournalEntry.generateEntryNumber(companyId);
      const period = await PeriodService.getOpenPeriodId(companyId, entryDate);

      // Build journal lines
      const lines = [
        {
          accountCode: liabilityAccount.code,
          accountName: liabilityAccount.name,
          description: 'Principal repayment',
          debit: principalPortion,
          credit: 0
        }
      ];

      if (interestPortion > 0) {
        // Debit 2800 Accrued Interest (clearing the accrued liability)
        const accruedInterestAccount = await ChartOfAccount.findOne({
          code: DEFAULT_ACCOUNTS.accruedInterest,
          company: companyId
        });
        if (accruedInterestAccount) {
          lines.push({
            accountCode: accruedInterestAccount.code,
            accountName: accruedInterestAccount.name,
            description: 'Interest payment (clearing accrued interest)',
            debit: interestPortion,
            credit: 0
          });
        } else {
          // Fallback: if 2800 not configured, use interest expense account
          if (!liability.interestExpenseAccountId) {
            throw new Error('INTEREST_ACCOUNT_NOT_CONFIGURED');
          }
          const interestAccount = await ChartOfAccount.findOne({
            _id: liability.interestExpenseAccountId,
            company: companyId
          });
          if (interestAccount) {
            lines.push({
              accountCode: interestAccount.code,
              accountName: interestAccount.name,
              description: 'Interest expense (direct — no prior accrual)',
              debit: interestPortion,
              credit: 0
            });
          }
        }
      }

      lines.push({
        accountCode: bankAccount.ledgerAccountId?.code || '1100',
        accountName: bankAccount.name || 'Cash at Bank',
        description: 'Payment to lender',
        debit: 0,
        credit: totalPayment
      });

      const journalEntry = await JournalEntry.create({
        company: companyId,
        entryNumber,
        date: entryDate,
        description: `Liability Repayment - ${liability.name} - ${liability.reference_no}`,
        sourceType: 'liability_repayment',
        sourceId: `${liabilityId}_${entryDate.toISOString()}`,
        reference: liability.reference_no,
        status: 'posted',
        lines,
        totalDebit: totalPayment,
        totalCredit: totalPayment,
        debitTotal: totalPayment,
        creditTotal: totalPayment,
        postedBy: userId,
        period: period,
        isAutoGenerated: false
      });

      // Create BankTransaction to reduce bank balance (withdrawal for repayment)
      try {
        await bankAccount.addTransaction({
          type: 'withdrawal',
          amount: totalPayment,
          description: `Liability repayment: ${liability.name} (${liability.reference_no})`,
          date: entryDate,
          referenceNumber: liability.reference_no,
          referenceType: 'Payment',
          reference: liability._id,
          createdBy: userId,
          journalEntryId: journalEntry._id
        });
        bankAccount.cacheValid = false;
        await bankAccount.save();
      } catch (btErr) {
        console.error('BankTransaction creation failed for liability repayment:', btErr.message);
      }

      // Add transaction record
      liability.transactions.push({
        transactionDate: entryDate,
        type: 'repayment',
        amount: totalPayment,
        principalPortion,
        interestPortion,
        bankAccountId: bankAccount._id,
        journalEntryId: journalEntry._id,
        notes: data.notes || null
      });

      // Update outstanding balance
      liability.outstandingBalance = liability.outstandingBalance - principalPortion;

      // Check if fully repaid
      if (liability.outstandingBalance <= 0.01) {
        liability.outstandingBalance = 0;
        liability.status = 'fully_repaid';
      }

      await liability.save();

      return liability;

    } catch (err) {
      throw err;
    }
  }

  // ── POST INTEREST ACCRUAL (no cash movement) ───────────────────────
  static async postInterest(companyId, liabilityId, data, userId) {
    const liability = await Liability.findOne({ _id: liabilityId, company_id: companyId });

    if (!liability) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    if (!liability.interestExpenseAccountId) {
      throw new Error('INTEREST_ACCOUNT_NOT_CONFIGURED');
    }

    const { amount, chargeDate } = data;

    // Validate accounts
    const liabilityAccount = await ChartOfAccount.findOne({ 
      _id: liability.liabilityAccountId, 
      company: companyId 
    });
    const interestAccount = await ChartOfAccount.findOne({ 
      _id: liability.interestExpenseAccountId, 
      company: companyId 
    });

    if (!liabilityAccount || !interestAccount) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    try {
      const entryDate = chargeDate ? new Date(chargeDate) : new Date();
      const entryNumber = await JournalEntry.generateEntryNumber(companyId);
      const period = await PeriodService.getOpenPeriodId(companyId, entryDate);

      // Look up Accrued Interest account (2800)
      const accruedInterestAccount = await ChartOfAccount.findOne({
        code: DEFAULT_ACCOUNTS.accruedInterest,
        company: companyId
      });

      if (!accruedInterestAccount) {
        throw new Error('ACCRUED_INTEREST_ACCOUNT_NOT_FOUND: Account 2800 Accrued Interest is required for interest accrual');
      }

      const journalEntry = await JournalEntry.create({
        company: companyId,
        entryNumber,
        date: entryDate,
        description: `Interest Accrual - ${liability.name} - ${liability.reference_no}`,
        sourceType: 'liability_interest',
        sourceId: `${liabilityId}_interest_${entryDate.toISOString()}`,
        reference: liability.reference_no,
        status: 'posted',
        lines: [
          {
            accountCode: interestAccount.code,
            accountName: interestAccount.name,
            description: 'Interest expense accrued',
            debit: amount,
            credit: 0
          },
          {
            accountCode: accruedInterestAccount.code,
            accountName: accruedInterestAccount.name,
            description: 'Interest accrued (2800)',
            debit: 0,
            credit: amount
          }
        ],
        totalDebit: amount,
        totalCredit: amount,
        debitTotal: amount,
        creditTotal: amount,
        postedBy: userId,
        period: period,
        isAutoGenerated: false
      });

      // Add transaction record
      liability.transactions.push({
        transactionDate: entryDate,
        type: 'interest_charge',
        amount: amount,
        journalEntryId: journalEntry._id,
        notes: data.notes || null
      });

      // Do NOT add accrued interest to outstandingBalance — 2800 tracks it separately

      await liability.save();

      return liability;

    } catch (err) {
      throw err;
    }
  }
}

module.exports = LiabilityService;
