const mongoose = require('mongoose');

// Journal Entry Line Schema (individual debit/credit lines)
const journalLineSchema = new mongoose.Schema({
  accountCode: { type: String, required: true, trim: true },
  accountName: { type: String, required: true, trim: true },
  description: { type: String, trim: true },
  debit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  credit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  reference: { type: String, trim: true },
  // For bank reconciliation - tracks if this line has been matched to a bank statement line
  reconciled: { type: Boolean, default: false },
  // Reference to matched bank statement line
  matchedStatementLineId: { type: mongoose.Schema.Types.ObjectId, default: null }
});

// Journal Entry Main Schema
const journalEntrySchema = new mongoose.Schema({
  // Company reference
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  
  // Entry details
  entryNumber: {
    type: String,
    required: true
  },
  date: {
    type: Date,
    required: true,
    default: Date.now
  },
  description: {
    type: String,
    required: true,
    trim: true
  },
  
  // Reference to source document (optional)
  sourceType: {
    type: String,
    enum: ['manual', 'invoice', 'invoice_cogs', 'purchase', 'purchase_order', 'credit_note', 'credit_note_cogs', 'expense', 'asset', 'asset_purchase', 'asset_disposal', 'depreciation', 'loan', 'payment', 'adjustment', 'petty_cash', 'petty_cash_topup', 'petty_cash_expense', 'petty_cash_replenishment', 'petty_cash_opening', 'purchase_return', 'stock_adjustment', 'payroll', 'payroll_run', 'payroll_salary', 'payroll_reversal', 'tax_payment', 'tax_settlement', 'vat_settlement', 'paye_settlement', 'rssb_settlement', 'bank_transfer', 'bank_deposit', 'bank_withdrawal', 'bank_account_opening', 'opening_balance', 'reversal', 'cogs', 'stock_transfer', 'stock_audit', 'cogs_adjustment', 'cogs_adjustment_reversal', 'ar_receipt', 'ar_receipt_reversal', 'bad_debt_writeoff', 'ap_payment', 'ap_payment_reversal', 'liability_drawdown', 'liability_repayment', 'liability_interest', 'other_income', 'tax_accrual', 'loan_interest', 'bank_charge', 'interest_accrual', 'distribution_cost', 'admin_expense', 'other_expense', 'oci', 'dividend', 'employee_advance', 'employee_advance_settlement', 'prepaid_expense', 'prepaid_expense_amortization', 'deferred_revenue', 'deferred_revenue_recognition', null],
    default: 'manual'
  },
  sourceId: {
    type: String,
    default: null
  },
  sourceReference: {
    type: String,
    trim: true
  },
  // Backwards-compatible top-level reference alias (some tests/query patterns)
  reference: {
    type: String,
    trim: true,
    default: null
  },
  
  // Entry lines (debits and credits)
  lines: [journalLineSchema],
  
  // Status
  status: {
    type: String,
    enum: ['draft', 'posted', 'voided', 'reversed'],
    default: 'draft'
  },
  
  // Totals (for validation) - use Decimal128 for monetary precision
  totalDebit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  totalCredit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  // Backwards-compatible stored aliases
  debitTotal: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  creditTotal: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  
  // Metadata
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  reversalOf: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  postedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  notes: {
    type: String,
    trim: true
  }
  ,
  // Reversal metadata
  reversed: {
    type: Boolean,
    default: false
  },

  // Bank Reconciliation tracking (real-world workflow)
  // These fields track if this entry was created/matched during reconciliation
  reconciliationStatus: {
    type: String,
    enum: ['unreconciled', 'reconciled', 'adjusting_entry'],
    default: 'unreconciled',
    index: true,
  },
  reconciledAt: {
    type: Date,
    default: null,
  },
  reconciledInReconciliationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BankReconciliation',
    default: null,
    index: true,
  },
  reconciledBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
  },
  // Whether this was an adjusting entry created during reconciliation
  isReconciliationAdjustingEntry: {
    type: Boolean,
    default: false,
  },
  reversedAt: {
    type: Date,
    default: null
  },
  reversedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  reversalEntryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  },

  // Locking fields for reconciliation audit trail
  // When a journal entry is matched during reconciliation, it gets locked
  // to prevent editing or deletion, maintaining accounting integrity
  isLocked: {
    type: Boolean,
    default: false,
    index: true,
  },
  lockedAt: {
    type: Date,
    default: null,
  },
  lockedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
  },
  lockedReason: {
    type: String,
    default: null,
  }
}, {
  // timestamps handled by auditSoftDeletePlugin to avoid duplicate field definitions
});

// Plugin for audit fields and soft-delete
const auditPlugin = require('./plugins/auditSoftDeletePlugin');
journalEntrySchema.plugin(auditPlugin);

// Convert Decimal128 results to JS numbers for compatibility with tests and lean queries
const decimalTransform = require('./plugins/decimalTransformPlugin');
journalEntrySchema.plugin(decimalTransform);

// Extra safety: ensure totals and line amounts are plain numbers after queries
function coerceDecimalField(val) {
  if (val == null) return 0;
  if (typeof val === 'number') return val;
  if (typeof val === 'string') return Number(val);
  if (val && typeof val === 'object') {
    if (val.$numberDecimal) return Number(val.$numberDecimal);
    try { return Number(val.toString()); } catch (e) { return 0; }
  }
  return Number(val) || 0;
}

function coerceJournalDoc(doc) {
  if (!doc) return;
  try {
    // Prefer operating on the underlying plain object when present
    const base = (doc._doc && typeof doc._doc === 'object') ? doc._doc : doc;
    if (base.totalDebit !== undefined) base.totalDebit = coerceDecimalField(base.totalDebit);
    if (base.totalCredit !== undefined) base.totalCredit = coerceDecimalField(base.totalCredit);
    if (Array.isArray(base.lines)) {
      base.lines.forEach(l => {
        if (l.debit !== undefined) l.debit = coerceDecimalField(l.debit);
        if (l.credit !== undefined) l.credit = coerceDecimalField(l.credit);
      });
    }
    // Backwards-compatible aliases expected by tests
    if (base.totalDebit !== undefined) base.debitTotal = base.totalDebit;
    if (base.totalCredit !== undefined) base.creditTotal = base.totalCredit;
  } catch (e) {
    // swallow; best-effort
  }
}

journalEntrySchema.post('find', function(docs) {
  if (!docs) return;
  for (const d of docs) coerceJournalDoc(d);
});

journalEntrySchema.post('findOne', function(doc) {
  coerceJournalDoc(doc);
});

journalEntrySchema.post('aggregate', function(result) {
  if (!result) return;
  for (const r of result) coerceJournalDoc(r);
});

// Use sequence service for gap-free entry numbers
const { nextSequence } = require('../services/sequenceService');

// Ensure Decimal128 fields serialize as strings with two decimals
journalEntrySchema.set('toJSON', {
  virtuals: true,
  transform: (doc, ret) => {
    const toStr = (val) => {
      if (val == null) return '0.00';
      try { return parseFloat(val.toString()).toFixed(2); } catch (e) { return String(val); }
    };
    if (ret.totalDebit !== undefined) ret.totalDebit = toStr(ret.totalDebit);
    if (ret.totalCredit !== undefined) ret.totalCredit = toStr(ret.totalCredit);
    // Backwards-compatible aliases
    if (ret.totalDebit !== undefined) ret.debitTotal = ret.totalDebit;
    if (ret.totalCredit !== undefined) ret.creditTotal = ret.totalCredit;
    if (Array.isArray(ret.lines)) {
      ret.lines = ret.lines.map(l => ({
        accountCode: l.accountCode,
        accountName: l.accountName,
        description: l.description,
        debit: toStr(l.debit),
        credit: toStr(l.credit),
        reference: l.reference
      }));
    }
    return ret;
  }
});

// Compound index for company + date
journalEntrySchema.index({ company: 1 });
journalEntrySchema.index({ company: 1, date: -1 });
journalEntrySchema.index({ company: 1, status: 1 });
journalEntrySchema.index({ company: 1, status: 1, date: 1 });
journalEntrySchema.index({ company: 1, sourceType: 1, date: 1 });
journalEntrySchema.index({ company: 1, entryNumber: 1 }, { unique: true });

// Index on embedded lines.accountCode for report queries (performance optimization)
journalEntrySchema.index({ company: 1, 'lines.accountCode': 1 });
journalEntrySchema.index({ company: 1, date: 1, 'lines.accountCode': 1 });
// Ensure we don't create duplicate journal entries for the same source event
// For depreciation, we allow multiple entries per asset by including the year-month in the unique key
// This allows monthly depreciation entries while preventing duplicate postings for the same period
journalEntrySchema.index(
  { company: 1, sourceType: 1, sourceId: 1, date: 1 },
  {
    unique: true,
    // Use $type (not $ne: null) so partial indexes work on MongoDB versions used by mongodb-memory-server
    partialFilterExpression: { sourceId: { $type: 'string' } },
  },
);

// Pre-save middleware to calculate totals
journalEntrySchema.pre('save', function(next) {
  // Calculate totals from lines (handle Decimal128 values)
  try {
    const sumDebit = this.lines.reduce((sum, line) => {
      const v = line.debit && line.debit.toString ? parseFloat(line.debit.toString()) : Number(line.debit || 0);
      return sum + (isFinite(v) ? v : 0);
    }, 0);
    const sumCredit = this.lines.reduce((sum, line) => {
      const v = line.credit && line.credit.toString ? parseFloat(line.credit.toString()) : Number(line.credit || 0);
      return sum + (isFinite(v) ? v : 0);
    }, 0);

    // Store as Decimal128 strings to preserve precision
    this.totalDebit = mongoose.Types.Decimal128.fromString(sumDebit.toFixed(2));
    this.totalCredit = mongoose.Types.Decimal128.fromString(sumCredit.toFixed(2));

    // Mirror totals into backwards-compatible alias fields
    this.debitTotal = this.totalDebit;
    this.creditTotal = this.totalCredit;

    // Ensure top-level reference mirrors sourceReference for compatibility
    if (this.sourceReference) this.reference = this.sourceReference;

    // Validate balanced entry - fail fast if not balanced
    if (Math.abs(sumDebit - sumCredit) > 0.01) {
      return next(new Error('Journal entry is not balanced: totalDebit != totalCredit'));
    }
    next();
  } catch (err) {
    return next(err);
  }
});

// Prevent updates to posted or locked entries via findOneAndUpdate / updateOne
journalEntrySchema.pre('findOneAndUpdate', async function(next) {
  try {
    const query = this.getQuery();
    const doc = await this.model.findOne(query).lean();
    if (doc && doc.isLocked) {
      return next(new Error('Cannot modify a locked journal entry. This entry has been reconciled and is locked for audit trail integrity.'));
    }
    if (doc && doc.status === 'posted') {
      return next(new Error('Cannot modify a posted journal entry'));
    }
    next();
  } catch (err) {
    next(err);
  }
});

// Prevent updates to locked entries on save
journalEntrySchema.pre('save', async function(next) {
  // Skip for new documents
  if (this.isNew) return next();

  try {
    // Check if document exists and is locked
    const existing = await this.constructor.findById(this._id).lean();
    if (existing && existing.isLocked) {
      return next(new Error('Cannot modify a locked journal entry. This entry has been reconciled and is locked for audit trail integrity.'));
    }
    next();
  } catch (err) {
    next(err);
  }
});

// Prevent deletions of posted or locked entries via deleteOne / deleteMany
journalEntrySchema.pre('deleteOne', { document: false, query: true }, async function(next) {
  try {
    const query = this.getQuery();
    const doc = await this.model.findOne(query).lean();
    if (doc && doc.isLocked) {
      return next(new Error('Cannot delete a locked journal entry. This entry has been reconciled and is locked for audit trail integrity.'));
    }
    if (doc && doc.status === 'posted') {
      return next(new Error('Cannot delete a posted journal entry'));
    }
    next();
  } catch (err) {
    next(err);
  }
});

// Static method to generate entry number
journalEntrySchema.statics.generateEntryNumber = async function(companyId) {
  const year = new Date().getFullYear();
  const seq = await nextSequence(companyId, 'journal_entry');
  const companyPrefix = String(companyId).slice(-4).toUpperCase();
  return `JE-${companyPrefix}-${year}-${seq}`;
};

// Method to validate debits equal credits
journalEntrySchema.methods.isBalanced = function() {
  const td = this.totalDebit && this.totalDebit.toString ? parseFloat(this.totalDebit.toString()) : Number(this.totalDebit || 0);
  const tc = this.totalCredit && this.totalCredit.toString ? parseFloat(this.totalCredit.toString()) : Number(this.totalCredit || 0);
  return Math.abs(td - tc) < 0.01;
};

// Static method to get trial balance
journalEntrySchema.statics.getTrialBalance = async function(companyId, startDate, endDate) {
  const query = { 
    company: companyId, 
    status: 'posted',
    date: { $gte: startDate, $lte: endDate }
  };
  
  const entries = await this.find(query);
  
  const accountBalances = {};
  
  entries.forEach(entry => {
    entry.lines.forEach(line => {
      const code = line.accountCode;
      if (!accountBalances[code]) {
        accountBalances[code] = {
          code,
          name: line.accountName,
          debit: 0,
          credit: 0,
          balance: 0
        };
      }
      
      accountBalances[code].debit += line.debit || 0;
      accountBalances[code].credit += line.credit || 0;
    });
  });
  
  // Calculate balances based on normal balance
  Object.values(accountBalances).forEach(account => {
    // This will be adjusted based on account type in the report
    account.balance = account.debit - account.credit;
  });
  
  return accountBalances;
};

const JournalEntry = mongoose.model('JournalEntry', journalEntrySchema);

module.exports = JournalEntry;
